#
# Makefile for Assignment 5 for 5613 C programming
# Use: make or make clean to compile 
#
# D. Sheridan
# V 1.0
# 28-Nov-2025
#

#typing 'make' will build both programs.
all: assignment5a assignment5b

# Assignment 5B
assignment5b: assignment5b.c matrix.o simulation.o stats.o random.o file_io.o
	gcc -Wall -Wextra -o assignment5b assignment5b.c matrix.o simulation.o stats.o random.o file_io.o -lm

#Assignment 5A
assignment5a: assignment5a.c file_io.o stats.o random.o
	gcc -Wall -Wextra -o assignment5a assignment5a.c file_io.o stats.o random.o -lm

matrix.o: matrix.c matrix.h
	gcc -Wall -Wextra -c matrix.c

simulation.o: simulation.c simulation.h
	gcc -Wall -Wextra -c simulation.c

stats.o: stats.c stats.h
	gcc -Wall -Wextra -c stats.c

random.o: random.c random.h
	gcc -Wall -Wextra -c random.c

file_io.o: file_io.c file_io.h
	gcc -Wall -Wextra -c file_io.c

.PHONY: all clean

clean:
	# Removes both executables, all .o files, and any .txt files generated by the sim
	rm -f assignment5a assignment5b *.o *.txt
